@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.3 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Jun 02 00:54:33 +0800 2019
REM SW Build 2405991 on Thu Dec  6 23:38:27 MST 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim top_sim_time_synth -key {Post-Synthesis:sim_1:Timing:top_sim} -tclbatch top_sim.tcl -view C:/Users/HBat/Desktop/20174240黄敏轩_实验四摩尔状态机序列检测器/project_4/moorefsm_sim_behav.wcfg -view C:/Users/HBat/Desktop/20174240黄敏轩_实验四摩尔状态机序列检测器/project_4/top_sim_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
